module.exports = {
  "apps": [
    {
      "name": "manageai-build-api",
      "script": "/opt/manageai/build-api/server.js",
      "cwd": "/opt/manageai/build-api",
      "max_memory_restart": "512M",
      "env": {
        "NODE_ENV": "production",
        "PORT": 3000,
        "COCKPIT_KEY": "friday-cockpit-2026",
        "ANTHROPIC_API_KEY": "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",
        "SUPABASE_URL": "https://fmemdogudiolevqsfuvd.supabase.co",
        "SUPABASE_SERVICE_KEY": "sb_secret_2YsDL4w7MSDCofglnAw-3g_ptYtwWKy",
        "AZURE_TENANT_ID": "b09a1fba-3225-4ea8-9e4f-8a7bf4f41fef",
        "AZURE_CLIENT_ID": "46883fdc-e018-4b5e-9250-76037f1ab8e0",
        "AZURE_CLIENT_SECRET": "2qt8Q~SKWOrgmg7Bhnq0_QDtyjrO4tntHfE_1a27",
        "GRAPH_USER_EMAIL": "brian@manageai.io",
        "ONEDRIVE_USER_EMAIL": "brian@manageai.io",
        "DAN_EMAIL": "dan@manageai.io",
        "DAVE_EMAIL": "dave@manageai.io",
        "BRIAN_EMAIL": "brian@manageai.io",
        "BRIAN_GMAIL": "brianreinhart3617@gmail.com",
        "FRIDAY_PUBLIC_URL": "http://5.223.79.255:3000",
        "N8N_LOCAL_URL": "http://localhost:5678",
        "N8N_LOCAL_API_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk",
        "CHARLIE_SERVER_URL": "http://5.223.60.100:3001",
        "GITHUB_TOKEN": "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",
        "GITHUB_ORG": "Brian2169fdsa",
        "TEMPORAL_ADDRESS": "localhost:7233",
        "SUPABASE_KEY": "sb_secret_2YsDL4w7MSDCofglnAw-3g_ptYtwWKy",
        "FRIDAY_TEAMS_WEBHOOK_URL": "",
        "NOTIFICATIONS_MODE": "teams",
        "GITHUB_PAT": "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",
        "GITHUB_USERNAME": "Brian2169fdsa",
        "WEBHOOK_URL": "",
        "CHARLIE_FACTORY_URL": "http://5.223.60.100:3001"
      }
    },
    {
      "name": "ttyd",
      "script": "/usr/bin/ttyd",
      "args": "-p 7682 bash"
    },
    {
      "name": "friday-worker",
      "script": "/opt/manageai/build-api/temporal/worker.js",
      "cwd": "/opt/manageai/build-api",
      "node_args": "--max-old-space-size=512",
      "interpreter_args": "--max-old-space-size=512",
      "max_memory_restart": "512M",
      "env": {
        "NODE_OPTIONS": "--max-old-space-size=512",
        "NODE_ENV": "production",
        "ANTHROPIC_API_KEY": "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",
        "SUPABASE_URL": "https://fmemdogudiolevqsfuvd.supabase.co",
        "SUPABASE_SERVICE_KEY": "sb_secret_2YsDL4w7MSDCofglnAw-3g_ptYtwWKy",
        "AZURE_TENANT_ID": "b09a1fba-3225-4ea8-9e4f-8a7bf4f41fef",
        "AZURE_CLIENT_ID": "46883fdc-e018-4b5e-9250-76037f1ab8e0",
        "AZURE_CLIENT_SECRET": "2qt8Q~SKWOrgmg7Bhnq0_QDtyjrO4tntHfE_1a27",
        "GRAPH_USER_EMAIL": "brian@manageai.io",
        "ONEDRIVE_USER_EMAIL": "brian@manageai.io",
        "DAN_EMAIL": "dan@manageai.io",
        "DAVE_EMAIL": "dave@manageai.io",
        "BRIAN_EMAIL": "brian@manageai.io",
        "FRIDAY_PUBLIC_URL": "http://5.223.79.255:3000",
        "N8N_LOCAL_URL": "http://localhost:5678",
        "N8N_LOCAL_API_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk",
        "CHARLIE_SERVER_URL": "http://5.223.60.100:3001",
        "GITHUB_TOKEN": "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",
        "GITHUB_ORG": "Brian2169fdsa",
        "TEMPORAL_ADDRESS": "localhost:7233",
        "SUPABASE_KEY": "sb_secret_2YsDL4w7MSDCofglnAw-3g_ptYtwWKy",
        "FRIDAY_TEAMS_WEBHOOK_URL": "",
        "NOTIFICATIONS_MODE": "teams",
        "GITHUB_PAT": "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",
        "GITHUB_USERNAME": "Brian2169fdsa",
        "WEBHOOK_URL": "",
        "CHARLIE_FACTORY_URL": "http://5.223.60.100:3001"
      }
    }
  ]
}