module.exports = {
  apps: [
    {
      name: 'manageai-build-api',
      script: '/opt/manageai/build-api/server.js',
      cwd: '/opt/manageai/build-api',
      // Process stability -- takes effect on next restart
      max_memory_restart: '512M',
      node_args: '--max-old-space-size=384',
      kill_timeout: 10000,
      listen_timeout: 10000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        BRIAN_EMAIL: 'build@manageai.io',
        ANTHROPIC_API_KEY: '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',
        AZURE_TENANT_ID: 'b09a1fba-3225-4ea8-9e4f-8a7bf4f41fef',
        AZURE_CLIENT_ID: '46883fdc-e018-4b5e-9250-76037f1ab8e0',
        AZURE_CLIENT_SECRET: '2qt8Q~SKWOrgmg7Bhnq0_QDtyjrO4tntHfE_1a27',
        GRAPH_USER_EMAIL: 'brian@manageai.io',
        DAN_EMAIL: 'dan@manageai.io',
        DAVE_EMAIL: 'dave@manageai.io',
        ONEDRIVE_USER_EMAIL: 'brian@manageai.io',
        SUPABASE_URL: 'https://fmemdogudiolevqsfuvd.supabase.co',
        SUPABASE_SERVICE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW1kb2d1ZGlvbGV2cXNmdXZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzcwNTQ2MiwiZXhwIjoyMDg5MjgxNDYyfQ.PXBm_m4Qcf2izPmh2d_loiFGfUKlqKqm4QhyY2x89BA',
        N8N_WF07_CALLBACK: 'http://localhost:5678/webhook/wf-07-callback',
        N8N_LOCAL_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk',
        N8N_LOCAL_URL: 'http://localhost:5678',
        N8N_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk',
        CHARLIE_SERVER_URL: 'http://5.223.60.100:3001',
        FRIDAY_TEAMS_WEBHOOK_URL: 'https://managepartners.webhook.office.com/webhookb2/f5564ad3-eabb-4fe6-aa8e-7cd229ffee51@b09a1fba-3225-4ea8-9e4f-8a7bf4f41fef/IncomingWebhook/1e944b1563a64476bc807f61cd6ff881/fe8c7679-5769-4c6e-aeb9-29bb01ca9bb5/V2JoRMwLdPYgsZi18UlwdoBRQBftIM8t3DGNTI8Lp198M1',
        FRIDAY_TEAMS_CHANNEL_ID: '19:-D4rZwmVAYiuYQooltsxSk1ZePzIF3lj0sJ838fM-_01@thread.tacv2',
        FRIDAY_PUBLIC_URL: 'http://5.223.79.255:3000',
        NOTIFICATIONS_MODE: 'factory',
        GITHUB_ORG: 'Brian2169fdsa',
        GITHUB_TOKEN: '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',
      }
    },
    // NOTE: n8n removed 2026-04-10 — was crash-looping (exit code 1) and killing PM2 daemon.
    // n8n is managed separately. Re-add when n8n database/config is fixed.
    // {
    //   name: 'n8n',
    //   script: '/usr/bin/n8n',
    //   env: {
    //     N8N_PORT: 5678,
    //     N8N_PROTOCOL: 'http',
    //     N8N_HOST: '0.0.0.0',
    //     WEBHOOK_URL: 'http://5.223.79.255:5678/',
    //   }
    // },
    {
      name: 'ttyd',
      script: '/usr/bin/ttyd',
      args: '-p 7682 bash',
    },
    {
      name: 'friday-worker',
      script: '/opt/manageai/build-api/temporal/worker.js',
      cwd: '/opt/manageai/build-api',
      // Process stability -- takes effect on next restart
      max_memory_restart: '512M',
      kill_timeout: 10000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        BRIAN_EMAIL: 'build@manageai.io',
        ANTHROPIC_API_KEY: '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',
        SUPABASE_URL: 'https://fmemdogudiolevqsfuvd.supabase.co',
        SUPABASE_SERVICE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW1kb2d1ZGlvbGV2cXNmdXZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzcwNTQ2MiwiZXhwIjoyMDg5MjgxNDYyfQ.PXBm_m4Qcf2izPmh2d_loiFGfUKlqKqm4QhyY2x89BA',
        N8N_WF07_CALLBACK: 'http://localhost:5678/webhook/wf-07-callback',
        N8N_LOCAL_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk',
        N8N_LOCAL_URL: 'http://localhost:5678',
        N8N_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk',
        CHARLIE_SERVER_URL: 'http://5.223.60.100:3001',
        CHARLIE_FACTORY_URL: 'http://5.223.60.100:3002',
        FRIDAY_TEAMS_WEBHOOK_URL: 'https://managepartners.webhook.office.com/webhookb2/f5564ad3-eabb-4fe6-aa8e-7cd229ffee51@b09a1fba-3225-4ea8-9e4f-8a7bf4f41fef/IncomingWebhook/1e944b1563a64476bc807f61cd6ff881/fe8c7679-5769-4c6e-aeb9-29bb01ca9bb5/V2JoRMwLdPYgsZi18UlwdoBRQBftIM8t3DGNTI8Lp198M1',
        FRIDAY_TEAMS_CHANNEL_ID: '19:-D4rZwmVAYiuYQooltsxSk1ZePzIF3lj0sJ838fM-_01@thread.tacv2',
        FRIDAY_PUBLIC_URL: 'http://5.223.79.255:3000',
        NOTIFICATIONS_MODE: 'factory',
        GITHUB_ORG: 'Brian2169fdsa',
        GITHUB_TOKEN: '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',
        AZURE_TENANT_ID: 'b09a1fba-3225-4ea8-9e4f-8a7bf4f41fef',
        AZURE_CLIENT_ID: '46883fdc-e018-4b5e-9250-76037f1ab8e0',
        AZURE_CLIENT_SECRET: '2qt8Q~SKWOrgmg7Bhnq0_QDtyjrO4tntHfE_1a27',
        GRAPH_USER_EMAIL: 'brian@manageai.io',
        DAN_EMAIL: 'dan@manageai.io',
        DAVE_EMAIL: 'dave@manageai.io',
        ONEDRIVE_USER_EMAIL: 'brian@manageai.io',
      }
    },
    // BUILD-013: Build Intelligence Layer
    {
      name: 'build-watcher',
      script: '/opt/manageai/build-api/build-watcher.js',
      cwd: '/opt/manageai/build-api',
      max_memory_restart: '256M',
      kill_timeout: 5000,
      exp_backoff_restart_delay: 100,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        SUPABASE_URL: 'https://fmemdogudiolevqsfuvd.supabase.co',
        SUPABASE_SERVICE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW1kb2d1ZGlvbGV2cXNmdXZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzcwNTQ2MiwiZXhwIjoyMDg5MjgxNDYyfQ.PXBm_m4Qcf2izPmh2d_loiFGfUKlqKqm4QhyY2x89BA',
      }
    },
    {
      name: 'diagnostic-agent',
      script: '/opt/manageai/build-api/diagnostic-agent.js',
      cwd: '/opt/manageai/build-api',
      max_memory_restart: '256M',
      kill_timeout: 5000,
      exp_backoff_restart_delay: 100,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        SUPABASE_URL: 'https://fmemdogudiolevqsfuvd.supabase.co',
        SUPABASE_SERVICE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW1kb2d1ZGlvbGV2cXNmdXZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzcwNTQ2MiwiZXhwIjoyMDg5MjgxNDYyfQ.PXBm_m4Qcf2izPmh2d_loiFGfUKlqKqm4QhyY2x89BA',
        FRIDAY_PUBLIC_URL: 'http://5.223.79.255:3000',
        N8N_LOCAL_URL: 'http://localhost:5678',
        N8N_LOCAL_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MGRhMjA0ZS0xNWJlLTQ2NjItODg0NC0wYTRhNGZlYjI2OTMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYzc2OWIxZjUtNmQ0My00ZDJiLTg4NDUtYjUwMmMzOTU0OThiIiwiaWF0IjoxNzc0NzU3MDEwfQ.-XDZXIgSb8OJPeHC-mlFHlE0m_1ksL6UZinxvaycHnk',
      }
    },
    {
      name: 'research-agent',
      script: '/opt/manageai/build-api/research-agent.js',
      cwd: '/opt/manageai/build-api',
      max_memory_restart: '256M',
      kill_timeout: 5000,
      exp_backoff_restart_delay: 100,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        BRIAN_EMAIL: 'build@manageai.io',
        ANTHROPIC_API_KEY: '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',
        SUPABASE_URL: 'https://fmemdogudiolevqsfuvd.supabase.co',
        SUPABASE_SERVICE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW1kb2d1ZGlvbGV2cXNmdXZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzcwNTQ2MiwiZXhwIjoyMDg5MjgxNDYyfQ.PXBm_m4Qcf2izPmh2d_loiFGfUKlqKqm4QhyY2x89BA',
        GITHUB_ORG: 'Brian2169fdsa',
        GITHUB_TOKEN: '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',
      }
    }
  ]
};
